options:
  substitution_option: ALLOW_LOOSE
steps:

  - name: 'gcr.io/k8s-testimages/gcb-docker-gcloud:v20200422-b25d964'
    entrypoint: bash
    env:
      - TAG=$_GIT_TAG
      - REGISTRY=gcr.io/k8s-staging-ingressconformance
    args:
    - -c
    - |
      gcloud auth configure-docker \
      && make build-image publish-image build-image publish-image

substitutions:
  _GIT_TAG: "12345"
  _PULL_BASE_REF: "master"
