---

apiVersion: v1
kind: Service
metadata:
  name: qotm
spec:
  selector:
    app: qotm
  ports:
    - name: http
      port: 80
      targetPort: http-api

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: qotm
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: qotm
  template:
    metadata:
      labels:
        app: qotm
    spec:
      containers:
        - name: qotm
          image: datawire/qotm:1.7
          imagePullPolicy: Always
          ports:
            - name: http-api
              containerPort: 5000
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 3
          resources:
            limits:
              cpu: "0.1"
              memory: 100Mi